#!/usr/bin/env node

// Next exports the generated Open Graph card without an extension. Static hosts
// infer its Content-Type from the filename, so give the PNG a stable `.png` URL
// and update the metadata references generated by Next.

import { readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs'

const ROOT = new URL('../', import.meta.url)
const OUT = new URL('out/', ROOT)
const SOURCE = new URL('opengraph-image', OUT)
const TARGET = new URL('opengraph-image.png', OUT)

const png = readFileSync(SOURCE)
if (png.subarray(1, 4).toString('latin1') !== 'PNG') {
  throw new Error('out/opengraph-image is not a PNG')
}

renameSync(SOURCE, TARGET)

const TEXT_FILE = /\.(html|json|xml|txt|js|css|webmanifest)$/
const GENERATED_URL = /\/opengraph-image(?!\.png)(?:\?[a-z0-9]+)?/gi
let replacements = 0

function rewrite(dir = OUT) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const url = new URL(entry.name + (entry.isDirectory() ? '/' : ''), dir)
    if (entry.isDirectory()) {
      rewrite(url)
      continue
    }
    if (!TEXT_FILE.test(entry.name)) continue

    const source = readFileSync(url, 'utf8')
    const output = source.replace(GENERATED_URL, () => {
      replacements += 1
      return '/opengraph-image.png'
    })
    if (output !== source) writeFileSync(url, output)
  }
}

rewrite()

if (replacements === 0) {
  throw new Error('no generated Open Graph image URL was found in out/')
}

console.log(`Finalized out/opengraph-image.png and rewrote ${replacements} metadata reference(s).`)
